In [2]:
import numpy as np 
a = [1,2,3] 
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1,2,3,'5', 4.5] 
b = np.array(a, dtype= str)
print(b)

['1' '2' '3' '5' '4.5']


In [4]:
a = [1,2,3] 
b = np.array(a * 3)
print(b)

[1 2 3 1 2 3 1 2 3]


In [5]:
b = np.ones(3, dtype=int)
print(b)

[1 1 1]


In [6]:
b = np.zeros(3, dtype=int)
print(b)

[0 0 0]


In [7]:
b = np.ones((2,3),dtype=int)    # 2 is rows and 3 is columns
print(b)

[[1 1 1]
 [1 1 1]]


In [8]:
b = np.full(3,5,dtype=float)   # 3 is size,,, 5 is value 
b

array([5., 5., 5.])

In [9]:
b = np.full((2,3), 5, dtype = int)
b

array([[5, 5, 5],
       [5, 5, 5]])

In [10]:
b = np.empty(4, dtype=int)
print(b)

[-1257580620  -453756294   613361971  1868216442]


assignment 

In [11]:
list = [[1,2,3],[4,5,6],[7,8,9]]
b= np.array(list)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
b = np.arange(10)    # start is included and end is excluded
b                    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.arange(2,10, 2)   # 3 steps inbtw [2,10)
b

array([2, 4, 6, 8])

In [22]:
b = np.linspace(2,10)   # provides 50 sample by default  [2,10]
print(b)       
print(b[1]- b[0])
print(b[32]- b[31])

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
0.16326530612244916
0.16326530612244916


In [16]:
b = np.linspace(2, 10, 5, dtype=str)    # no of samples is 5 both end points included by default unless specified
b

array(['2.0', '4.0', '6.0', '8.0', '10.0'], dtype='<U32')

In [17]:
b = np.linspace(2, 10, 5, dtype=str, endpoint=False)
print(b)                # here endpoint is exclusive

['2.0' '3.6' '5.2' '6.800000000000001' '8.4']


In [18]:
b = np.identity(4)  # identity matrix of n x n 
b  

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
b = np.eye(3)    #identity matrix of m x n
print(b)
a = np.eye(2,2)
print(a)
c = np.eye(5,6)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [20]:
a = np.random.rand(3)   # three samples btw 0 and 1
print(a)
b = np.random.rand(2,3)
print('printing b')
print(b)

[0.17210158 0.29743176 0.71277564]
printing b
[[0.47348838 0.85185726 0.0981865 ]
 [0.7911845  0.96326872 0.25062806]]


In [21]:
#if we want to change the range 
a = np.random.rand(10)*10
a

array([2.11723193, 5.11320565, 8.45333704, 4.43997678, 7.69713225,
       6.70470045, 9.46186456, 1.03518825, 2.80475359, 8.36189362])