In [10]:
import numpy as np

li = [1,2,3]
arr = np.array(li)
print(li)
print(arr)
print(arr.dtype)
print(arr.strides)   #how many bytes for the element 

[1, 2, 3]
[1 2 3]
int32
(4,)


In [11]:
li_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr_2d = np.array(li_2d)
print(li_2d)
print(arr_2d)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int32
(12, 4)


In [15]:
print(li[2])
print(arr[2])
print(li[1:3])
print(arr[1:3])

3
3
[2, 3]
[2 3]


In [18]:
print(li_2d[1][1])
print(arr_2d[1][1])
print(arr_2d[1,1])   # same as above

5
5
5


In [23]:
print(li_2d[1][0:2])
print(arr_2d[1, :2])

[4, 5]
[4 5]


In [51]:
print(li_2d[0:1][0])           ####     [[1,2,3],
print(li_2d[0:2])              ####     [4,5,6],
                                #       [7,8,9]]

[1, 2, 3]
[[1, 2, 3], [4, 5, 6]]


however numpy arrays works as normal

In [54]:
print(arr_2d[0:2, 2])
print(arr_2d[0:1,1:3])

[3 6]
[[2 3]]


In [70]:
li = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
print(li[2][0:3])
arr = np.array(li)
print(li[1][2:4])
print(arr[1, 2:4])

[11, 12, 13]
[8, 9]
[8 9]
