In [69]:
import numpy as np
import random

li = [1,2,3,4,5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[2 5 1 3 1]
[ 9 18 15  9  5]


In [70]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [71]:
a = a +1
a

array([3, 6, 2, 4, 2])

In [72]:
c = a +b
c

array([12, 24, 17, 13,  7])

In [73]:
d = a - b
d

array([ -6, -12, -13,  -5,  -3])

In [74]:
e = a * b
e

array([ 27, 108,  30,  36,  10])

In [75]:
f = a  / b
print (f)
print(a//b)
print(a**b)

[0.33333333 0.33333333 0.13333333 0.44444444 0.4       ]
[0 0 0 0 0]
[     19683 1159987200      32768     262144         32]


In [76]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[3 6 2 4 2]
17
3.4
2
2
6
1


In [77]:
print(a)
print(b)

[3 6 2 4 2]
[ 9 18 15  9  5]


In [78]:
print(a>b)
print(a<b)
print(a==b)

[False False False False False]
[ True  True  True  True  True]
[False False False False False]


In [79]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))      #unary operator

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]
