In [25]:
import numpy as np 
a = np . array(['t', 'b','r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 2  9  5 16  2  1  7  3]


In [26]:
print(b>10)

[False False False  True False False False False]


In [27]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]

new_arr

[False False False  True False False False False]


array([16])

In [28]:
new_arr = b[(b > 10) & ( b < 18)]
new_arr

array([16])

In [44]:
print(b)
print(a)
# ind = np.where(b == 2)
# print(ind)
print(a[np.where(b ==2)])

[ 2  9  5 16  2  1  7  3]
['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
['t' 'e']
