broadcasting (operation over different sized array)
compatable :::if:::
1) equal
2) one of them is 1

In [1]:
import numpy as np
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[7 3 9]
 [5 7 4]
 [1 4 5]]
[[1 2 1]
 [2 7 3]
 [2 2 8]]


In [2]:
ans = x-y
ans

array([[ 6,  1,  8],
       [ 3,  0,  1],
       [-1,  2, -3]])

In [3]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))   
print(x)
print(y)

[[3 8 7]
 [6 1 4]
 [4 4 5]]
[4 9 9]


In [4]:
ans = x -y    # y is made compatable with the x by broadcasting the rows (repeat) to match its dimensions
ans  

array([[-1, -1, -2],
       [ 2, -8, -5],
       [ 0, -5, -4]])

In [5]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))   
print(x)
print(y)

[[7 7]
 [5 8]
 [4 5]]
[[4 6 7]
 [9 7 2]]


In [6]:
y = np.transpose(y)
np.shape(y)
ans = x -y 
ans 

array([[ 3, -2],
       [-1,  1],
       [-3,  3]])

In [7]:
a = np.random.randint(1, 10,(3,1))
b = np.random.randint(1, 10,(3,3))
print(a)
print(b)

[[7]
 [7]
 [7]]
[[5 8 8]
 [9 6 7]
 [5 9 9]]


In [8]:
ans = a - b 
ans 

array([[ 2, -1, -1],
       [-2,  1,  0],
       [ 2, -2, -2]])

In [9]:
a = np.random.randint(1, 10,(1,3))
b = np.random.randint(1, 10,(3,1))
print(a)
print(b)
print(a-b)

[[5 2 3]]
[[8]
 [2]
 [1]]
[[-3 -6 -5]
 [ 3  0  1]
 [ 4  1  2]]


In [10]:
a = np.random.randint(1, 10,(1,3))
b = np.random.randint(1, 10,(1))
print(a)
print(b)
print(a - b)

[[6 4 5]]
[5]
[[ 1 -1  0]]


In [11]:
a = np.random.randint(1, 10,(3,1))
b = np.random.randint(1, 10,(1,3))
print(a)
print(b)
print(a - b)

[[7]
 [9]
 [7]]
[[4 3 4]]
[[3 4 3]
 [5 6 5]
 [3 4 3]]


examples of broadcasting 

In [12]:

import numpy as np 
import csv
open_file = open('this.csv')
data = csv.DictReader(open_file,skipinitialspace=True)
for i in data : 
    print(i)

{'Year': '1970', 'Month': '7', 'Day': '2', 'Country': 'Dominican Republic', 'State': '', 'Region': 'Central America & Caribbean', 'City': 'Santo Domingo', 'Latitude': '18.456792', 'Longitude': '-69.951164', 'AttackType': 'Assassination', 'Killed': '1.0', 'Wounded': '0.0', 'Target': 'Julio Guzman', 'Summary': '', 'Group': 'MANO-D', 'Target_type': 'Private Citizens & Property', 'Weapon_type': 'Unknown'}
{'Year': '1970', 'Month': '0', 'Day': '0', 'Country': 'Mexico', 'State': 'Federal', 'Region': 'North America', 'City': 'Mexico city', 'Latitude': '19.371887', 'Longitude': '-99.086624', 'AttackType': 'Hostage Taking (Kidnapping)', 'Killed': '0.0', 'Wounded': '0.0', 'Target': 'Nadine Chaval, daughter', 'Summary': '', 'Group': '23rd of September Communist League', 'Target_type': 'Government (Diplomatic)', 'Weapon_type': 'Unknown'}
{'Year': '1970', 'Month': '1', 'Day': '0', 'Country': 'Philippines', 'State': 'Tarlac', 'Region': 'Southeast Asia', 'City': 'Unknown', 'Latitude': '15.47859800000

In [13]:
country = []
wounded = []
killed = []
for i in data: 
    country.append(i['Country'])
    print(i['Country'])
    wounded.append(i['Wounded'])
    killed.append(i['Killed'])

In [14]:
np_killed = np.array(killed, dtype=int)
np_country = np.array(country)
np_wounded = np.array(wounded)
print(np_killed)
print(np_country)
print(np_wounded)

[]
[]
[]
